apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-default
spec:
  profile: default
  values:
    global:
      tracer:
        zipkin:
          address: zipkin:9411