apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  targetNamespace: monitoring
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki-stack
    version: 2.1.0
  values:
    grafana:
      enabled: true